language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
# command to run tests
script:
  - pytest --cov
  after_success: coveralls